version: "3.8"

services:

##########################################################################################################################
  CitizenAccountManagement:
    image: openjdk:17-jdk-alpine
    container_name: CitizenAccountManagement
    ports:
      - 8080:8080
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - mongoCitizensDB
    networks:
      - my-net
    volumes:
      - ./CitizenAccountManagement/build/libs/CitizenAccountManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  mongoCitizensDB:
    image: mongo:5.0
    container_name: mongoCitizensDB
    ports:
      - 27017:27017
    networks:
      - my-net

##########################################################################################################################
  AdminAccountManagement:
    image: openjdk:17-jdk-alpine
    container_name: AdminAccountManagement
    ports:
      - 8081:8080
      - 8001:8000
    expose:
      - "8000"
    depends_on:
      - mongoAdminsDB
    networks:
      - my-net
    volumes:
      - ./AdminAccountManagement/build/libs/AdminAccountManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  mongoAdminsDB:
    image: mongo:5.0
    container_name: mongoAdminsDB
    ports:
      - 27018:27017
    networks:
      - my-net

##########################################################################################################################
  DumpsterManagement:
    image: openjdk:17-jdk-alpine
    container_name: DumpsterManagement
    ports:
      - 8082:8080
      - 8002:8000
    expose:
      - "8000"
      - "8080"
    depends_on:
      - mongoDumpstersDB
      - SmartDumpsters
      - rabbitmq
    networks:
      - my-net
    volumes:
      - ./DumpsterManagement/build/libs/DumpsterManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  mongoDumpstersDB:
    image: mongo:5.0
    container_name: mongoDumpstersDB
    ports:
      - 27019:27017
    networks:
      - my-net

##########################################################################################################################
  WasteManagement:
    image: openjdk:17-jdk-alpine
    container_name: WasteManagement
    ports:
      - 8083:8080
      - 8003:8000
    expose:
      - "8000"
    depends_on:
      - mongoWastesDB
    networks:
      - my-net
    volumes:
      - ./WasteManagement/build/libs/WasteManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  mongoWastesDB:
    image: mongo:5.0
    container_name: mongoWastesDB
    ports:
      - 27020:27017
    networks:
      - my-net


##########################################################################################################################
  PaymentManagement:
    image: openjdk:17-jdk-alpine
    container_name: PaymentManagement
    ports:
      - 8084:8080
      - 8004:8000
    expose:
      - "8000"
    depends_on:
      - mongoPaymentsDB
    networks:
      - my-net
    volumes:
      - ./PaymentManagement/build/libs/PaymentManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  mongoPaymentsDB:
    image: mongo:5.0
    container_name: mongoPaymentsDB
    ports:
      - 27021:27017
    networks:
      - my-net

##########################################################################################################################

  SmartDumpsters:
    image: openjdk:17-jdk-alpine
    container_name: SmartDumpsters
    ports:
      - 8085:8080
      - 8005:8000
    expose:
      - "8000"
    networks:
      - my-net
    depends_on:
      - rabbitmq
    volumes:
      - ./SmartDumpsters/build/libs/SmartDumpsters-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  ##########################################################################################################################
  EmailtManagement:
    image: openjdk:17-jdk-alpine
    container_name: EmailManagement
    ports:
      - 8086:8080
      - 8006:8000
    expose:
      - "8000"
    depends_on:
      - SmartDumpsters
    networks:
      - my-net
    volumes:
      - ./EmailManagement/build/libs/EmailManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

##########################################################################################################################

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.7
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-net



networks:
  my-net:
    driver:
      "bridge"

